apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-multifile
  name: gitops-multifile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-multifile
  template:
    metadata:
      labels:
        app: gitops-multifile
    spec:
      containers:
        - name: nodeserver
          image: quay.io/ecotz/sampleapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi
          restartPolicy: Always