apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-multifile
  name: gitops-multifile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-multifile
  template:
    metadata:
      labels:
        app: gitops-multifile
    spec:
      containers:
        - env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: "95"
          image: default-route-openshift-image-registry.apps.itz-00jsp6.infra01-lb.dal14.techzone.ibm.com/openshift-image-registry/application-simple-gitops:latest
          imagePullPolicy: Always
          name: gitops-multifile-1
          resources:
            limits:
              cpu: 50m
              memory: 28Mi
            requests:
              cpu: 50m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-credentials
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30