apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openshift-gitops
  template:
    metadata:
      labels:
        app: openshift-gitops
    spec:
      containers:
        - name: nodeserver
          image: quay.io/ecotz/gitopsapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi
          restartPolicy: Always