apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:  application-simple-gitops
  name: application-simple-gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application-simple-gitops
  template:
    metadata:
      labels:
        app: application-simple-gitops
    spec:
      containers:
        - env:
            - name: RUN_TYPE
              value: cpu
            - name: CPU_PERCENT
              value: "95"
          image: default-route-openshift-image-registry.apps.itz-00jsp6.infra01-lb.dal14.techzone.ibm.com/openshift-image-registry/application-simple-gitops:latest
          imagePullPolicy: Always
          name: application-simple-gitops
          resources:
            limits:
              cpu: 120m
              memory: 15Gi
            requests:
              cpu: 120m
              memory: 15Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: default-dockercfg-t9jl9
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30