apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: /gitops
  newTag: 7569f6d0b5ff68118a15c3c851faccd830e1a4d4
