apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: /gitops
  newTag: 752762a3e4426bd1bda2cf1db2abe2fbab1474a1
