apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: nodeserver
  newName: /gitops
  newTag: ce9bac5d057b51714c7b30abd94ec350b0cad2dd
