apiVersion: v1
kind: Service
metadata:
  name: gitops-multifile-service
  labels:
    app: gitops-multifile
spec:
  selector:
    app: gitops-multifile
  ports:
    - port: 8080
      targetPort: 8080