apiVersion: v1
kind: Service
metadata:
  name: application-simple-gitops-service
  labels:
    app: application-simple-gitops
spec:
  selector:
    app: application-simple-gitops
  ports:
    - port: 8080
      targetPort: 8080