apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bb-gitops-turbonomic
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-image-registry
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/igooruh/pipeline-argocd
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
