apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-multifile
  namespace: openshift-gitops
spec:
  destination:
    namespace: argocd-test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops-multifile
    repoURL: https://github.com/igooruh/pipeline-argocd
    targetRevision: develop
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
